export interface AdventureTemplate {
  id: string;
  title: string;
  levelRange: string;
  setting: string;
  startingLocation: string;
  antagonistName: string;
  antagonistMotivation: string;
  openingHook: string;
  description: string;
  factions: Array<{ name: string; stance: 'ally' | 'neutral' | 'hostile' }>;
  tags: string[];
  gradient: string;
}

export const ADVENTURE_TEMPLATES: AdventureTemplate[] = [
  {
    id: 'wdh',
    title: 'Waterdeep: Dragon Heist',
    levelRange: '1–5',
    setting: 'Forgotten Realms',
    startingLocation: 'Waterdeep, the City of Splendors',
    antagonistName: 'Xanathar',
    antagonistMotivation: 'Seize the Cache of Dragons and destroy rival factions',
    openingHook: 'A brawl at the Yawning Portal pulls the party into a citywide conspiracy over half a million gold dragons',
    description: 'A half-million gold dragons are hidden in Waterdeep. Faction war erupts over the prize.',
    factions: [
      { name: 'Harpers', stance: 'ally' },
      { name: 'Zhentarim', stance: 'neutral' },
      { name: "Xanathar's Guild", stance: 'hostile' },
    ],
    tags: ['city', 'intrigue', 'heist'],
    gradient: 'from-purple-950 via-indigo-900 to-purple-950',
  },
  {
    id: 'idrotf',
    title: 'Icewind Dale: Rime of the Frostmaiden',
    levelRange: '1–12',
    setting: 'Forgotten Realms',
    startingLocation: 'Ten-Towns, Icewind Dale',
    antagonistName: 'Auril the Frostmaiden',
    antagonistMotivation: 'Shroud the world in eternal winter and be worshipped as the sole surviving deity',
    openingHook: "Auril has blotted out the sun over Icewind Dale — Ten-Towns slowly freezes as the party arrives",
    description: 'The goddess Auril plunges Icewind Dale into eternal winter. The party must end her reign before the last town falls.',
    factions: [
      { name: 'Arcane Brotherhood', stance: 'hostile' },
      { name: 'Reghed Nomads', stance: 'neutral' },
      { name: "Dwarves of Kelvin's Cairn", stance: 'ally' },
    ],
    tags: ['horror', 'wilderness', 'survival'],
    gradient: 'from-blue-950 via-slate-900 to-blue-950',
  },
  {
    id: 'veor',
    title: 'Vecna: Eve of Ruin',
    levelRange: '10–20',
    setting: 'Multiplanar (Sigil and beyond)',
    startingLocation: 'Sigil, the City of Doors',
    antagonistName: 'Vecna, the Undying King',
    antagonistMotivation: 'Unmake the multiverse and remake it in his image',
    openingHook: 'The Lady of Pain summons the party to Sigil — Vecna has assembled the Rod of Seven Parts and the multiverse is fracturing',
    description: 'Vecna is on the verge of godhood and plans to unmake reality. The party must stop him across the planes.',
    factions: [
      { name: 'Fraternity of Order', stance: 'neutral' },
      { name: 'Harmonium', stance: 'neutral' },
      { name: 'Athar', stance: 'ally' },
    ],
    tags: ['multiplanar', 'epic', 'horror'],
    gradient: 'from-violet-950 via-stone-900 to-violet-950',
  },
  {
    id: 'lmop',
    title: 'Lost Mine of Phandelver',
    levelRange: '1–5',
    setting: 'Forgotten Realms',
    startingLocation: 'Phandalin, a frontier town near Neverwinter',
    antagonistName: 'Nezznar the Black Spider',
    antagonistMotivation: 'Claim the magical forge of spells in Wave Echo Cave for personal power',
    openingHook: 'A supply run to Phandalin goes wrong — the dwarven employers are missing and goblins have ambushed the road',
    description: 'A classic starter adventure. Find the lost mine, save the town, and face the Black Spider.',
    factions: [
      { name: 'Harpers', stance: 'ally' },
      { name: "Lords' Alliance", stance: 'neutral' },
      { name: 'Redbrand Ruffians', stance: 'hostile' },
    ],
    tags: ['dungeon-crawl', 'starter', 'classic'],
    gradient: 'from-emerald-950 via-stone-900 to-emerald-950',
  },
  {
    id: 'cos',
    title: 'Curse of Strahd',
    levelRange: '1–10',
    setting: 'Barovia (Ravenloft)',
    startingLocation: 'Barovia Village, the realm of Barovia',
    antagonistName: 'Strahd von Zarovich',
    antagonistMotivation: 'Possess Ireena Kolyana, the reincarnation of his lost love Tatyana',
    openingHook: 'The party is lured into the mist-shrouded realm of Barovia — escape is impossible until Strahd is destroyed',
    description: 'Trapped in the gothic realm of Barovia, the party must destroy the vampire lord Strahd or be enslaved forever.',
    factions: [
      { name: 'Vistani', stance: 'neutral' },
      { name: 'Order of the Silver Dragon', stance: 'ally' },
      { name: 'Village of Barovia', stance: 'neutral' },
    ],
    tags: ['horror', 'gothic', 'sandbox'],
    gradient: 'from-red-950 via-stone-900 to-red-950',
  },
  {
    id: 'dia',
    title: 'Descent into Avernus',
    levelRange: '1–13',
    setting: 'Forgotten Realms / Avernus (Nine Hells)',
    startingLocation: "Baldur's Gate",
    antagonistName: 'Zariel',
    antagonistMotivation: 'Wage eternal war in Avernus and drag Elturel into Hell as a trophy',
    openingHook: "The city of Elturel vanishes into the Nine Hells — the party must follow it into Avernus to bring it back",
    description: "Follow Elturel into the Nine Hells, survive Avernus, and stop the fallen angel Zariel's war machine.",
    factions: [
      { name: 'Flaming Fist', stance: 'neutral' },
      { name: 'Hellriders', stance: 'ally' },
      { name: 'Cult of Zariel', stance: 'hostile' },
    ],
    tags: ['hellscape', 'war', 'epic'],
    gradient: 'from-orange-950 via-red-950 to-stone-900',
  },
  {
    id: 'toa',
    title: 'Tomb of Annihilation',
    levelRange: '1–11',
    setting: 'Chult (Forgotten Realms)',
    startingLocation: 'Port Nyanzaru, Chult',
    antagonistName: 'Acererak the Demilich',
    antagonistMotivation: 'Feed souls to the Soulmonger to fuel his undead apotheosis',
    openingHook: 'A death curse is killing all who have ever been resurrected — the source is somewhere deep in the jungles of Chult',
    description: 'A death curse is undoing all resurrections. Race through the jungles of Chult to destroy the Soulmonger.',
    factions: [
      { name: 'Merchant Princes of Port Nyanzaru', stance: 'neutral' },
      { name: 'Flaming Fist', stance: 'neutral' },
      { name: 'Undead', stance: 'hostile' },
    ],
    tags: ['jungle', 'death-curse', 'exploration'],
    gradient: 'from-green-950 via-yellow-950 to-stone-900',
  },
  {
    id: 'wbtw',
    title: 'Wild Beyond the Witchlight',
    levelRange: '1–8',
    setting: 'The Feywild',
    startingLocation: 'The Witchlight Carnival',
    antagonistName: 'The Hourglass Coven',
    antagonistMotivation: 'Each hag hoards stolen dreams and refuses to return what the party seeks',
    openingHook: 'The Witchlight Carnival has returned — the party senses something was stolen from them long ago and follows it into the Feywild',
    description: 'Something was stolen from you as a child. Follow the Witchlight Carnival into the Feywild to reclaim it.',
    factions: [
      { name: "Zybilna's Court", stance: 'neutral' },
      { name: 'Korreds', stance: 'ally' },
      { name: 'Hourglass Coven', stance: 'hostile' },
    ],
    tags: ['feywild', 'whimsy', 'mystery'],
    gradient: 'from-pink-950 via-fuchsia-950 to-purple-950',
  },
  {
    id: 'skt',
    title: "Storm King's Thunder",
    levelRange: '1–11',
    setting: 'Forgotten Realms (Sword Coast + North)',
    startingLocation: 'Nightstone, a small town near Waterdeep',
    antagonistName: 'Iymrith the Ancient Blue Dragon',
    antagonistMotivation: 'Sow chaos among the giant lords to prevent any one giant king from rising to power',
    openingHook: 'Giants are attacking settlements across the North — the ordning (giant hierarchy) has shattered and no one knows why',
    description: 'Giants rampage across the Sword Coast. Unravel the conspiracy behind the shattered ordning before civilization falls.',
    factions: [
      { name: "Lords' Alliance", stance: 'ally' },
      { name: 'Harpers', stance: 'ally' },
      { name: 'Giant Lords', stance: 'hostile' },
    ],
    tags: ['giants', 'open-world', 'epic'],
    gradient: 'from-sky-950 via-slate-900 to-stone-900',
  },
  {
    id: 'oota',
    title: 'Out of the Abyss',
    levelRange: '1–15',
    setting: 'The Underdark',
    startingLocation: 'Velkenvelve, a drow outpost deep in the Underdark',
    antagonistName: 'Demon Lords',
    antagonistMotivation: 'The demon lords have been summoned into the Underdark and spread madness through its depths',
    openingHook: 'The party wakes in chains in a drow prison — they must escape the Underdark before demon lords consume it',
    description: 'Escape from drow captivity in the Underdark while demon lords tear it apart around you.',
    factions: [
      { name: 'Drow of House Baenre', stance: 'hostile' },
      { name: 'Emerald Enclave', stance: 'ally' },
      { name: 'Gnomes of Blingdenstone', stance: 'ally' },
    ],
    tags: ['underdark', 'survival', 'demon-lords'],
    gradient: 'from-purple-950 via-indigo-950 to-slate-900',
  },
  {
    id: 'pota',
    title: 'Princes of the Apocalypse',
    levelRange: '1–15',
    setting: 'Forgotten Realms (Dessarin Valley)',
    startingLocation: 'Red Larch, Dessarin Valley',
    antagonistName: 'The Elder Elemental Eye',
    antagonistMotivation: 'Free the elder elemental princes and remake the world in primal chaos',
    openingHook: 'Strange things are happening in the Dessarin Valley — missing delegations, weird weather, and cults spreading through the countryside',
    description: 'Four elemental cults seek to unleash catastrophic power on the Sword Coast. Stop them before the prophets summon their gods.',
    factions: [
      { name: 'Harpers', stance: 'ally' },
      { name: 'Emerald Enclave', stance: 'ally' },
      { name: 'Crushing Wave', stance: 'hostile' },
    ],
    tags: ['elemental', 'dungeon-crawl', 'open-world'],
    gradient: 'from-amber-950 via-stone-900 to-teal-950',
  },
  {
    id: 'hotdq',
    title: 'Hoard of the Dragon Queen',
    levelRange: '1–8',
    setting: 'Forgotten Realms (Sword Coast)',
    startingLocation: 'Greenest, a town under dragon attack',
    antagonistName: 'Severin Silrajin',
    antagonistMotivation: "Collect the Dragon Hoard to fund Tiamat's return from the Nine Hells",
    openingHook: 'A blue dragon and the Cult of the Dragon attack Greenest — the party arrives as the town burns',
    description: 'The Cult of the Dragon is assembling a hoard to free Tiamat. Stop them before the Dragon Queen returns.',
    factions: [
      { name: 'Harpers', stance: 'ally' },
      { name: "Lords' Alliance", stance: 'ally' },
      { name: 'Cult of the Dragon', stance: 'hostile' },
    ],
    tags: ['dragons', 'tyranny', 'epic'],
    gradient: 'from-yellow-950 via-orange-950 to-red-950',
  },
  {
    id: 'gos',
    title: 'Ghosts of Saltmarsh',
    levelRange: '1–12',
    setting: 'Greyhawk (Saltmarsh)',
    startingLocation: 'Saltmarsh, a fishing town on the Azure Sea',
    antagonistName: 'The Scarlet Brotherhood',
    antagonistMotivation: "Destabilize Saltmarsh's trade routes and gain control of the Azure Sea",
    openingHook: 'A haunted mansion on the cliffs above Saltmarsh hides something far more dangerous than ghosts',
    description: "Saltmarsh faces threats from land and sea — smugglers, sea creatures, and a spy network conspiring against the town.",
    factions: [
      { name: 'Saltmarsh Council', stance: 'ally' },
      { name: 'Scarlet Brotherhood', stance: 'hostile' },
      { name: 'Sahuagin', stance: 'hostile' },
    ],
    tags: ['nautical', 'investigation', 'anthology'],
    gradient: 'from-teal-950 via-blue-950 to-slate-900',
  },
  {
    id: 'kftgv',
    title: 'Keys from the Golden Vault',
    levelRange: '1–11',
    setting: 'Various (anthology)',
    startingLocation: 'The Golden Vault (mysterious benefactor)',
    antagonistName: 'Varies per mission',
    antagonistMotivation: 'The Golden Vault sends the party on heist missions for unknown but ostensibly good reasons',
    openingHook: 'A golden music box appears with a key inside — and instructions for a job that must go perfectly',
    description: 'Thirteen heist missions from a mysterious benefactor. Steal, infiltrate, and outmaneuver in style.',
    factions: [
      { name: 'The Golden Vault', stance: 'ally' },
      { name: 'Targets vary', stance: 'hostile' },
    ],
    tags: ['heist', 'anthology', 'one-shots'],
    gradient: 'from-amber-950 via-yellow-950 to-stone-900',
  },
  {
    id: 'lox',
    title: 'Spelljammer: Light of Xaryxis',
    levelRange: '5–8',
    setting: 'Wildspace / Astral Sea',
    startingLocation: 'A port city attacked from space',
    antagonistName: 'Emperor Xeleth',
    antagonistMotivation: 'Drain the life force of entire worlds to power their dying sun',
    openingHook: 'Astral elves descend from the sky and drain the life from the earth — the party must take the fight to space',
    description: 'Chase astral elves across the cosmos to stop them from killing your home world.',
    factions: [
      { name: 'Giff', stance: 'ally' },
      { name: 'Rock Gnomes', stance: 'ally' },
      { name: 'Xaryxian Empire', stance: 'hostile' },
    ],
    tags: ['spelljammer', 'space', 'action'],
    gradient: 'from-indigo-950 via-violet-950 to-slate-900',
  },
  {
    id: 'tso',
    title: 'Phandelver and Below: The Shattered Obelisk',
    levelRange: '1–12',
    setting: 'Forgotten Realms (Phandalin region)',
    startingLocation: 'Phandalin',
    antagonistName: 'Ilvaash the Godlet',
    antagonistMotivation: 'Shatter an ancient obelisk to open a portal to the Far Realm and transform all life into mind flayers',
    openingHook: 'Phandalin is under attack by mind flayers — and something in the Far Realm is pulling the strings',
    description: 'A Far Realm horror threatens Phandalin and all life beyond it. Stop the mind flayer cult before the portal opens.',
    factions: [
      { name: 'Harpers', stance: 'ally' },
      { name: 'Emerald Enclave', stance: 'ally' },
      { name: 'Cult of Ilvaash', stance: 'hostile' },
    ],
    tags: ['psionic', 'illithid', 'horror'],
    gradient: 'from-violet-950 via-purple-950 to-slate-900',
  },
];

export const ADVENTURE_TAGS = ['All', 'City', 'Horror', 'Dungeon', 'Wilderness', 'Heist', 'Multiplanar', 'Space'] as const;
export type AdventureTag = typeof ADVENTURE_TAGS[number];
